### ISSUE TITLE
publishable gifs

### ISSUE THREAD

**Issue by danhillreports** [statesman/ut-tower-shooting-50th#27]
of matterport and video for social

**Comment by cjwinchester** [comment]
![vizgif](https://cloud.githubusercontent.com/assets/3728252/16780234/674c55e0-483b-11e6-8462-173db2e4e3de.gif)
![matterport-gif](https://cloud.githubusercontent.com/assets/3728252/16780239/6debb40e-483b-11e6-8119-b9947fc8fd42.gif)
