### ISSUE TITLE
duplicate images in archival slideshows

### ISSUE THREAD

**Issue by cjwinchester** [statesman/ut-tower-shooting-50th#71]
we have three versions of the the "puff of smoke" picture, feels like overkill

**Comment by critmcdonald** [comment]
I can pull these.

**Comment by cjwinchester** [comment]
baller

the caption on one of them is wrong, too, as robert pointed out:

"Gunfire smoke from Charles Whitman during the shooting." should be

"A puff of dust is visible at the University of Texas Tower during the sniper attack."

or whatever, there are three to pick from ... might be worth doing a quick dupe check through all of them?

**Comment by critmcdonald** [comment]
I pulled one of the puffers
