### ISSUE TITLE
static nav peeks above content on xs

### ISSUE THREAD

**Issue by critmcdonald** [statesman/ut-tower-shooting-50th#90]
Dan noted that the top of the page peaks above the nav on phones.

![img_4443](https://cloud.githubusercontent.com/assets/4553750/16782777/b97c35f0-4846-11e6-9cfb-9a884d027975.PNG)

**Comment by cjwinchester** [comment]
probably related to [this](https://github.com/statesman/ut-tower-shooting-50th/commit/a176bc6781ce400637e392e7cc540bd23c9e42f4)

**Comment by critmcdonald** [comment]
Christian doesn't care anymore. Chrome only on iOS 6.
