### ISSUE TITLE
Video switch problems in IE

### ISSUE THREAD

**Issue by critmcdonald** [statesman/ut-tower-shooting-50th#91]
Video switching for the index and the interviews page is not working in IE 11. It does work in Firefox and Chrome on PC.

**Comment by cjwinchester** [comment]
borked on IE11 on my home laptop, as well -- not sure whether IE is just telling me that it made a successful CORS request (which, good job, i guess?) or if it's not able to execute it.

![image](https://cloud.githubusercontent.com/assets/3728252/16791963/61211310-4889-11e6-8b2e-e25c2a1c3f57.png)


on the q/a page, getting the same exception we saw earlier on click: `TypeError("The element or ID supplied is not valid. (videojs)"`

**Comment by cjwinchester** [comment]
This is a dumpster fire. In IE, playing a video in another player while a different one is going causes the video to freeze when un-paused.

**Comment by cjwinchester** [comment]
New issue: "Not enough space" brightcove craziness on IE

**Comment by critmcdonald** [comment]
@cjwinchester and @danhillreports licked this one. Take that, IE!

**Comment by cjwinchester** [comment]
for posterity, [instantiating an empty variable](https://github.com/statesman/ut-tower-shooting-50th/blob/master/src/js/front.js#L15-L16) and then setting its value to [`this`](https://github.com/statesman/ut-tower-shooting-50th/blob/master/src/js/front.js#L41-L44) is what made the difference
