### ISSUE TITLE
Add tease for sliders

### ISSUE THREAD

**Issue by critmcdonald** [statesman/ut-tower-shooting-50th#97]
We'll need a tease on the archive page to get folks to the then/now sliders.

**Comment by critmcdonald** [comment]
Branch https://github.com/statesman/ut-tower-shooting-50th/tree/thennowtease has a start of this. Needs screenshot once that ins done.

**Comment by cjwinchester** [comment]
<img width="643" alt="before-after-tease" src="https://cloud.githubusercontent.com/assets/3728252/16811074/47c8042e-48ec-11e6-8f6c-d6d90694b374.png">

**Comment by critmcdonald** [comment]
I think this will be ready to merge once the then/now project is published.
